Position michael
AutonomousCarProject/auto_racer pull request #78
Opened 2019-07-22 22:11 UTC by eatdacarrot

position tracking now working (with placeholders for distance between axles and circumference of wheels). Included a testmap.txt so ther eis no longer an error from racing line

2019-07-22 22:14 UTC, KevinPaulsen commented
This branch does not compile. Once Fixed, this branch can be approved.

2019-07-23 06:15 UTC, flseaui approved these changes

2019-07-23 06:18 UTC, rewinded commented
not comfortable merging this into master right now because it currently breaks update loop

2019-07-23 06:19 UTC, flseaui requested changes
make sure this runs with traksim (pretty sure something in update is breaking)

2019-07-23 17:54 UTC, closed without merging